---
# Wemos LOLIN32
#
# An ESP32-based board with 4MB flash, Wi-Fi & Bluetooth
#
# https://www.wemos.cc/en/latest/d32/d32.html
#
substitutions:
  i2c_bus_a_sda: "33"
  i2c_bus_a_scl: "32"
  i2c_bus_b_sda: "23"
  i2c_bus_b_scl: "22"

esp32:
  board: esp32dev

packages:
  wifi: !include ../components/wifi.yaml

