---
# ESP32 WT32-ETH01
#
# WT32-ETH01 is an embedded serial port to Ethernet module based on ESP32
#
# http://www.wireless-tag.com/wp-content/uploads/2022/10/WT32-ETH01_datasheet_V1.3-en.pdf
#
substitutions:
  i2c_bus_a_sda: "15"
  i2c_bus_a_scl: "14"
  i2c_bus_b_sda: "04"
  i2c_bus_b_scl: "02"
  
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16
  
esp32:
  board: esp-wrover-kit