- id: '1667855934726'
  alias: 'Fermer volets coucher soleil '
  description: 'Ferme les volets roulants 15 min après le coucher du soleil '
  trigger:
  - platform: sun
    event: sunset
    offset: 00:15:00
  condition: []
  action:
  - service: cover.close_cover
    data: {}
    target:
      entity_id: cover.vr_general
  mode: single
- id: '1667940962264'
  alias: Zone Notification
  description: ''
  use_blueprint:
    path: homeassistant/notify_leaving_zone.yaml
    input:
      person_entity: person.thomas
      zone_entity: zone.maison
      notify_device: 6b2bbffd51050ec702281f101ce90bec
- id: '1669586212407'
  alias: Éclairage placard escalier
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.lumi_lumi_sensor_magnet_aq2_opening
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.escalier_placard_2
  mode: single
- id: '1669586289331'
  alias: Extinction éclairage placard escalier
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.lumi_lumi_sensor_magnet_aq2_opening
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.escalier_placard_2
  mode: single
- id: '1669586500452'
  alias: Éclairage cellier
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.lumi_lumi_sensor_magnet_aq2_opening_2
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: cover.vr_cellier
    state: closed
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.cellier_spots
  mode: single
- id: '1669586965200'
  alias: Éclairage entrée cuisine
  description: ''
  trigger:
  - device_id: 94f10a3d79b25b9d82a903e70bd953ab
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - if:
    - condition: state
      entity_id: light.cuisine_spots_plan_de_travail
      state: 'on'
    then:
    - service: light.turn_off
      data: {}
      target:
        entity_id: light.cuisine_spots_plan_de_travail
    else:
    - service: light.turn_on
      data: {}
      target:
        entity_id: light.cuisine_spots_plan_de_travail
  mode: single
- id: '1672266440012'
  alias: Lampe bureau
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.bp_bureau
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 0.5
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.yeelight_color_0x458bc59
  mode: single
- id: '1673644248347'
  alias: Cube
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.cube_158d0001038dce
    attribute: last_action
    to: rotate
  condition: []
  action:
  - service: light.turn_on
    data:
      rgb_color:
      - 255
      - 60
      - 0
    target:
      entity_id: light.gateway_light_34ce008bede9
  mode: single
- id: '1673734933477'
  alias: Cube 2
  description: ''
  trigger:
  - device_id: 2c446dcafdb0df7cc430ad8f01349807
    domain: zha
    platform: device
    type: device_flipped
    subtype: face_1
  condition: []
  action:
  - service: notify.moi
    data:
      message: Cube face 1
  mode: single
- id: '1673905915371'
  alias: Cycle lave-vaiselle
  description: Détecte le début et la fin du lave-vaiselle
  use_blueprint:
    path: sbyx/notify-or-do-something-when-an-appliance-like-a-dishwasher-or-washing-machine-finishes.yaml
    input:
      power_sensor: sensor.prise_lave_vaisselle_active_power
      starting_threshold: 3
      starting_hysteresis: 1
      finishing_threshold: 1900
      finishing_hysteresis: 60
      actions:
      - service: notify.maison
        data:
          message: Le lave vaisselle a terminé.
      - service: light.toggle
        data: {}
        target:
          entity_id: light.salon_eclairage_central
      - wait_for_trigger:
        - platform: numeric_state
          entity_id: sensor.consommation_lave_vaiselle
          for:
            hours: 0
            minutes: 1
            seconds: 0
          above: 1500
      - service: notify.maison
        data:
          message: 'Lave-vaisselle : fin prélavage. Début lavage'
      - wait_for_trigger:
        - platform: numeric_state
          entity_id: sensor.consommation_lave_vaiselle
          for:
            hours: 0
            minutes: 1
            seconds: 0
          below: 1500
      - service: notify.maison
        data:
          message: 'Lave vaisselle : fin lavage. Début rinçage. '
      - wait_for_trigger:
        - platform: numeric_state
          entity_id: sensor.consommation_lave_vaiselle
          for:
            hours: 0
            minutes: 1
            seconds: 0
          above: 1500
      - service: notify.maison
        data:
          message: 'Lave vaisselle : fin rinçage. Début séchage '
      pre_actions:
      - service: notify.maison
        data:
          message: Démarrage du lave-vaiselle.
      - service: light.toggle
        data: {}
        target:
          entity_id:
          - light.salon_eclairage_central
- id: '1674426498201'
  alias: Lave-vaisselle
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.prise_lave_vaisselle_active_power
    for:
      hours: 0
      minutes: 0
      seconds: 30
    above: 8
  condition: []
  action:
  - service: notify.moi
    data:
      message: 'Lave-vaisselle : Démarrage prélavage'
  - wait_for_trigger:
    - platform: numeric_state
      entity_id: sensor.prise_lave_vaisselle_active_power
      for:
        hours: 0
        minutes: 0
        seconds: 30
      above: 1500
  - service: notify.moi
    data:
      message: 'Lave-vaiselle : début lavage'
  - wait_for_trigger:
    - platform: numeric_state
      entity_id: sensor.prise_lave_vaisselle_active_power
      for:
        hours: 0
        minutes: 0
        seconds: 30
      below: 1500
  - service: notify.moi
    data:
      message: 'Lave-vaiselle : début de rinçage'
  - wait_for_trigger:
    - platform: numeric_state
      entity_id: sensor.prise_lave_vaisselle_active_power
      for:
        hours: 0
        minutes: 0
        seconds: 30
      above: 1500
    continue_on_timeout: true
  - service: notify.moi
    data:
      message: 'Lave-vaisselle : début de séchage'
  - wait_for_trigger:
    - platform: numeric_state
      entity_id: sensor.prise_lave_vaisselle_active_power
      for:
        hours: 1
        minutes: 0
        seconds: 30
      below: 1500
  - service: notify.moi
    data:
      message: 'Lave-vaisselle : Fin de cycle'
  mode: single
- id: '1674428527583'
  alias: testito
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.prise_lave_vaisselle_active_power
    for:
      hours: 0
      minutes: 0
      seconds: 1
    above: 5
  condition: []
  action:
  - service: notify.moi
    data:
      message: OK !
  mode: single
