- id: '1667855934726'
  alias: 'Fermer volets coucher soleil '
  description: 'Ferme les volets roulants 15 min après le coucher du soleil '
  trigger:
  - platform: sun
    event: sunset
    offset: 00:15:00
  condition: []
  action:
  - service: cover.close_cover
    target:
      entity_id:
      - cover.vr_bureau
      - cover.vr_cellier
      - cover.vr_chambre_1
      - cover.vr_chambre_2
      - cover.vr_chambre_3
      - cover.vr_escalier
      - cover.vr_palier
      - cover.vr_salle_de_jeu
    data: {}
  - if:
    - condition: state
      entity_id: binary_sensor.porte_fenetre_salon_verrouillee
      state: 'on'
    then:
    - service: cover.close_cover
      target:
        entity_id: cover.vr_porte_fenetre_salon
      data: {}
  - if:
    - condition: and
      conditions:
      - condition: state
        entity_id: binary_sensor.baie_cuisine_verrouillee_droite
        state: 'on'
      - condition: state
        entity_id: binary_sensor.baie_cuisine_verrouillee_gauche
        state: 'on'
    then:
    - service: cover.close_cover
      data: {}
      target:
        entity_id: cover.vr_cuisine
  - if:
    - condition: and
      conditions:
      - condition: state
        entity_id: binary_sensor.baie_salon_verrouillee_droite
        state: 'on'
      - condition: state
        entity_id: binary_sensor.baie_salon_verrouillee_gauche
        state: 'on'
    then:
    - service: cover.close_cover
      data: {}
      target:
        entity_id: cover.vr_salon
  mode: single
- id: '1667940962264'
  alias: Zone Notification
  description: ''
  use_blueprint:
    path: homeassistant/notify_leaving_zone.yaml
    input:
      person_entity: person.thomas
      zone_entity: zone.maison
      notify_device: 6b2bbffd51050ec702281f101ce90bec
- id: '1669586212407'
  alias: Éclairage placard escalier
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.lumi_lumi_sensor_magnet_aq2_opening
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.escalier_placard_2
  mode: single
- id: '1669586289331'
  alias: Extinction éclairage placard escalier
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.lumi_lumi_sensor_magnet_aq2_opening
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.escalier_placard_2
  mode: single
- id: '1669586500452'
  alias: Éclairage cellier
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.lumi_lumi_sensor_magnet_aq2_opening_2
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: cover.vr_cellier
    state: closed
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.cellier_spots
  mode: single
- id: '1669586965200'
  alias: Éclairage entrée cuisine
  description: ''
  trigger:
  - device_id: 94f10a3d79b25b9d82a903e70bd953ab
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - if:
    - condition: state
      entity_id: light.cuisine_spots_plan_de_travail
      state: 'on'
    then:
    - service: light.turn_off
      data: {}
      target:
        entity_id: light.cuisine_spots_plan_de_travail
    else:
    - service: light.turn_on
      data: {}
      target:
        entity_id: light.cuisine_spots_plan_de_travail
  mode: single
- id: '1672266440012'
  alias: Lampe bureau
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.bp_bureau
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 0.5
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.yeelight_color_0x458bc59
  mode: single
- id: '1673644248347'
  alias: Cube
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.cube_158d0001038dce
    attribute: last_action
    to: rotate
  condition: []
  action:
  - service: light.turn_on
    data:
      rgb_color:
      - 255
      - 60
      - 0
    target:
      entity_id: light.gateway_light_34ce008bede9
  mode: single
- id: '1673734933477'
  alias: Cube 2
  description: ''
  trigger:
  - device_id: 2c446dcafdb0df7cc430ad8f01349807
    domain: zha
    platform: device
    type: device_flipped
    subtype: face_1
  condition: []
  action:
  - service: notify.moi
    data:
      message: Cube face 1
  mode: single
- id: '1673905915371'
  alias: Cycle lave-vaiselle
  description: Détecte le début et la fin du lave-vaiselle
  use_blueprint:
    path: sbyx/notify-or-do-something-when-an-appliance-like-a-dishwasher-or-washing-machine-finishes.yaml
    input:
      power_sensor: sensor.prise_lave_vaisselle_active_power
      starting_threshold: 3
      starting_hysteresis: 1
      finishing_threshold: 1900
      finishing_hysteresis: 60
      actions:
      - service: notify.maison
        data:
          message: Le lave vaisselle a terminé.
      - service: light.toggle
        data: {}
        target:
          entity_id: light.salon_eclairage_central
      - wait_for_trigger:
        - platform: numeric_state
          entity_id: sensor.consommation_lave_vaiselle
          for:
            hours: 0
            minutes: 1
            seconds: 0
          above: 1500
      - service: notify.maison
        data:
          message: 'Lave-vaisselle : fin prélavage. Début lavage'
      - wait_for_trigger:
        - platform: numeric_state
          entity_id: sensor.consommation_lave_vaiselle
          for:
            hours: 0
            minutes: 1
            seconds: 0
          below: 1500
      - service: notify.maison
        data:
          message: 'Lave vaisselle : fin lavage. Début rinçage. '
      - wait_for_trigger:
        - platform: numeric_state
          entity_id: sensor.consommation_lave_vaiselle
          for:
            hours: 0
            minutes: 1
            seconds: 0
          above: 1500
      - service: notify.maison
        data:
          message: 'Lave vaisselle : fin rinçage. Début séchage '
      pre_actions:
      - service: notify.maison
        data:
          message: Démarrage du lave-vaiselle.
      - service: light.toggle
        data: {}
        target:
          entity_id:
          - light.salon_eclairage_central
- id: '1674426498201'
  alias: Lave-vaisselle
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.prise_lave_vaisselle_active_power
    for:
      hours: 0
      minutes: 0
      seconds: 30
    above: 8
  condition: []
  action:
  - service: notify.moi
    data:
      message: 'Lave-vaisselle : Démarrage prélavage'
  - wait_for_trigger:
    - platform: numeric_state
      entity_id: sensor.prise_lave_vaisselle_active_power
      for:
        hours: 0
        minutes: 0
        seconds: 30
      above: 1500
  - service: notify.moi
    data:
      message: 'Lave-vaiselle : début lavage'
  - wait_for_trigger:
    - platform: numeric_state
      entity_id: sensor.prise_lave_vaisselle_active_power
      for:
        hours: 0
        minutes: 0
        seconds: 30
      below: 1500
  - service: notify.moi
    data:
      message: 'Lave-vaiselle : début de rinçage'
  - wait_for_trigger:
    - platform: numeric_state
      entity_id: sensor.prise_lave_vaisselle_active_power
      for:
        hours: 0
        minutes: 0
        seconds: 30
      above: 1500
    continue_on_timeout: true
  - service: notify.moi
    data:
      message: 'Lave-vaisselle : début de séchage'
  - wait_for_trigger:
    - platform: numeric_state
      entity_id: sensor.prise_lave_vaisselle_active_power
      for:
        hours: 1
        minutes: 0
        seconds: 30
      below: 1500
  - service: notify.moi
    data:
      message: 'Lave-vaisselle : Fin de cycle'
  mode: single
- id: '1675635231758'
  alias: Détection sirène
  description: Avertit si la sirène intérieure est déclenchée
  trigger:
  - platform: state
    entity_id:
    - switch.sirene_interieure
    to: 'on'
  condition: []
  action:
  - service: notify.maison
    data:
      message: 'Déclenchement sirène intérieure ! '
  - service: notify.mobile_app_galaxy_s20_fe
    data:
      message: 'Déclenchement sirène intérieure ! '
  - service: notify.moi
    data:
      message: 'Déclenchement sirène intérieure ! '
  mode: single
- id: '1675635547927'
  alias: Extinction sirène intérieure
  description: Éteint la sirène intérieure au bout de 3min
  trigger:
  - platform: state
    entity_id:
    - switch.sirene_interieure
    to: 'on'
    for:
      hours: 0
      minutes: 3
      seconds: 0
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.sirene_interieure
  mode: single
- id: '1676238242545'
  alias: Extinction lumière placard escalier
  description: Extinction lumière placard escalier au bout d'1 min
  trigger:
  - platform: state
    entity_id:
    - light.escalier_placard_2
    to: 'on'
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.escalier_placard_2
  mode: single
- id: '1677092658855'
  alias: Alarme
  description: Gère les état de l'alarme
  trigger:
  - platform: state
    entity_id:
    - alarm_control_panel.alarme_maison
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: alarm_control_panel.alarme_maison
        state: arming
      sequence:
      - if:
        - condition: state
          entity_id: input_boolean.alarme_silencieuse
          state: 'off'
        then:
        - service: script.tts_ouvertures
          data:
            volume: 80
        - service: script.tts_google_home
          data:
            texte: L'alarme sera activée dès que la porte sera fermée
            volume: 80
            media_player_entity: media_player.sejour
    - conditions:
      - condition: state
        entity_id: alarm_control_panel.alarme_maison
        state: armed_away
      sequence:
      - service: script.notifie_ouvertures
        data: {}
      - if:
        - condition: state
          entity_id: input_boolean.alarme_silencieuse
          state: 'off'
        then:
        - service: script.tts_google_home
          data:
            texte: Alarme activée !
            volume: 80
            media_player_entity: media_player.sejour
      - service: automation.turn_on
        data: {}
        target:
          entity_id: automation.telegram_changement_capteur
    - conditions:
      - condition: state
        entity_id: alarm_control_panel.alarme_maison
        state: disarmed
      - condition: template
        value_template: '{{ (trigger.from_state.state != ''unavailable'') and (trigger.from_state
          is not none) }} '
      sequence:
      - service: siren.turn_off
        target:
          entity_id:
          - siren.pse03_v1_1_0_siren_2
          - siren.pse03_v1_1_0_siren
        data: {}
      - parallel:
        - if:
          - condition: state
            entity_id: input_boolean.alarme_silencieuse
            state: 'off'
          then:
          - service: siren.turn_on
            data:
              tone: '5'
              duration: '5'
            target:
              entity_id:
              - siren.pse03_v1_1_0_siren_2
              - siren.pse03_v1_1_0_siren
        - service: automation.turn_off
          data:
            stop_actions: true
          target:
            entity_id: automation.telegram_changement_capteur
        - if:
          - condition: state
            entity_id: input_boolean.alarme_silencieuse
            state: 'off'
          then:
          - service: script.tts_google_home
            data:
              texte: Alarme désactivée
              volume: 80
              media_player_entity: media_player.sejour
        - if:
          - condition: template
            value_template: '{{trigger.from_state.state == ''triggered''}}'
          then:
          - service: scene.turn_on
            target:
              entity_id: scene.lumieres_vr
            data: {}
      - service: siren.turn_off
        data: {}
        target:
          entity_id:
          - siren.pse03_v1_1_0_siren_2
          - siren.pse03_v1_1_0_siren
    - conditions:
      - condition: state
        entity_id: alarm_control_panel.alarme_maison
        state: pending
      - condition: state
        entity_id: input_boolean.alarme_silencieuse
        state: 'off'
      sequence:
      - service: script.turn_on
        data:
          variables:
            texte: Il reste 20 secondes pour désactiver l'alarme, 17, 16, 15, 14,
              13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0
            volume: 80
            media_player_entity: media_player.sejour
        target:
          entity_id: script.tts_google_home
      - service: siren.turn_on
        data:
          tone: '6'
        target:
          entity_id:
          - siren.pse03_v1_1_0_siren_2
          - siren.pse03_v1_1_0_siren
      - delay:
          seconds: 4
      - service: siren.turn_on
        data:
          tone: '6'
        target:
          entity_id:
          - siren.pse03_v1_1_0_siren_2
          - siren.pse03_v1_1_0_siren
      - delay:
          seconds: 3
      - repeat:
          while:
          - condition: state
            entity_id: alarm_control_panel.alarme_maison
            state: pending
          sequence:
          - service: siren.turn_on
            data:
              tone: '6'
            target:
              entity_id:
              - siren.pse03_v1_1_0_siren_2
              - siren.pse03_v1_1_0_siren
          - delay:
              seconds: 1
    - conditions:
      - condition: state
        entity_id: alarm_control_panel.alarme_maison
        state: triggered
      sequence:
      - parallel:
        - if:
          - condition: state
            entity_id: input_boolean.alarme_silencieuse
            state: 'off'
          then:
          - service: siren.turn_on
            data:
              tone: '1'
              duration: '600'
            target:
              entity_id:
              - siren.pse03_v1_1_0_siren_2
              - siren.pse03_v1_1_0_siren
        - service: scene.create
          data:
            scene_id: lumieres_vr
            snapshot_entities: '{{ expand(states)|selectattr(''domain'', ''in'', (''light'',
              ''cover''))|selectattr(''state'', ''ne'', ''unavailable'')| map(attribute=''entity_id'')|
              list }}

              '
        - service: notify.maison
          data:
            message: Alarme maison déclenchée !
            title: ALARME !
        - service: notify.mobile_app_galaxy_s20_fe
          data:
            message: Alarme maison déclenchée !
            title: ALARME !
        - service: notify.mobile_app_m2103k19pg
          data:
            message: Alarme maison déclenchée !
            title: ALARME !
        - if:
          - condition: template
            value_template: '{{trigger.from_state.state == ''pending''}}'
          then:
          - service: notify.maison
            data:
              message: Délai désactivation alarme dépassé !
      - repeat:
          while:
          - condition: state
            entity_id: alarm_control_panel.alarme_maison
            state: triggered
          sequence:
          - service: cover.open_cover
            data: {}
            target:
              entity_id: cover.vr_general
          - if:
            - condition: state
              entity_id: input_boolean.alarme_silencieuse
              state: 'off'
            then:
            - service: script.turn_on
              data:
                variables:
                  texte: Alarme déclenchée, appel police en cours !
                  volume: 100
                  media_player_entity: media_player.sejour
              target:
                entity_id: script.tts_google_home
          - service: script.allume_lumieres
            data: {}
  mode: restart
- id: '1677626292376'
  alias: Notify if door opens
  trigger:
  - platform: state
    entity_id: sensor.changement_capteurs
  condition:
  - condition: template
    value_template: '{{ trigger.to_state.state != '''' }}'
  action:
  - service: notify.moi
    data:
      message: '{{ state_attr(trigger.to_state.state, ''friendly_name'') }} {{ states(trigger.to_state.state)
        }}'
- id: '1677878113159'
  alias: Telegram changement capteur
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.baie_cuisine_fermee_droite
    - binary_sensor.baie_cuisine_verrouillee_droite
    - binary_sensor.baie_cuisine_fermee_gauche
    - binary_sensor.baie_cuisine_verrouillee_gauche
    - binary_sensor.baie_salon_fermee_droite
    - binary_sensor.baie_salon_fermee_gauche
    - binary_sensor.baie_salon_verrouillee_droite
    - binary_sensor.baie_salon_verrouillee_gauche
    - binary_sensor.fenetre_chambre_1_fermee_droite
    - binary_sensor.fenetre_chambre_1_verrouillee_droite
    - binary_sensor.fenetre_chambre_1_fermee_gauche
    - binary_sensor.fenetre_chambre_1_verrouillee_gauche
    - binary_sensor.fenetre_sdj_fermee_droite
    - binary_sensor.fenetre_sdj_verrouillee_droite
    - binary_sensor.fenetre_sdj_fermee_gauche
    - binary_sensor.fenetre_bureau_fermee_droite
    - binary_sensor.fenetre_bureau_verrouillee_droite
    - binary_sensor.fenetre_bureau_fermee_gauche
    - binary_sensor.fenetre_bureau_verrouillee_gauche
    - binary_sensor.fenetre_cellier_fermee
    - binary_sensor.fenetre_cellier_verrouillee
    - binary_sensor.porte_fenetre_salon_fermee
    - binary_sensor.porte_fenetre_salon_verrouillee
    - binary_sensor.fenetre_sdb_rdc_fermee
    - binary_sensor.fenetre_sdb_rdc_verrouillee
    - binary_sensor.fenetre_wc_rdc_fermee
    - binary_sensor.fenetre_wc_rdc_verrouillee
    - binary_sensor.fenetre_chambre_2_fermee_droite
    - binary_sensor.fenetre_chambre_2_verrouillee_droite
    - binary_sensor.fenetre_chambre_2_fermee_gauche
    - binary_sensor.fenetre_chambre_2_verrouillee_gauche
    - binary_sensor.fenetre_chambre_3_fermee_droite
    - binary_sensor.fenetre_chambre_3_verrouillee_droite
    - binary_sensor.fenetre_chambre_3_verrouillee_gauche
    - binary_sensor.fenetre_sdb_etage_fermee
    - binary_sensor.fenetre_sdb_etage_verrouillee
    - binary_sensor.fenetre_wc_etage_fermee
    - binary_sensor.fenetre_wc_etage_verrouillee
    - binary_sensor.fenetre_palier_fermee_droite
    - binary_sensor.fenetre_palier_verrouillee_droite
    - binary_sensor.fenetre_palier_fermee_gauche
    - binary_sensor.fenetre_palier_verrouillee_gauche
    - binary_sensor.fenetre_escalier_fermee
    - binary_sensor.fenetre_escalier_verrouillee
    - binary_sensor.porte_garage_fermee_gauche
    - binary_sensor.porte_garage_verrouillee_gauche
    - binary_sensor.porte_garage_verrouillee_droite
    - binary_sensor.fenetre_garage_fermee
    - binary_sensor.capteur_presence_bureau
  condition: []
  action:
  - service: notify.maison
    data:
      message: '{{ state_attr(trigger.entity_id, ''friendly_name'') }} {{ trigger.to_state.state
        }}

        '
  mode: single
