esphome:
  name: esphome-aldes #esphome-web-24b704
  friendly_name: ESPhome Aldes #ESPHome Web 24b704
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

web_server:
  port: 80
  
# It is highly recommended to use secrets
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key 

# Allow Over-The-Air updates
ota:
- platform: esphome

# Deux connexions Modbus: La carte mère et la commande centrale (Remote)  
uart:
  - id: uart_motherboard
    baud_rate: 19200
    tx_pin: GPIO16  
    rx_pin: GPIO17  
    parity: EVEN
  - id: uart_central_command
    baud_rate: 19200
    tx_pin: GPIO3  
    rx_pin: GPIO1  
    parity: EVEN

# Modbus configuration
modbus:
  - uart_id: uart_motherboard
    id: modbus_motherboard
  - uart_id: uart_central_command
    id: modbus_central_command

modbus_controller:
  - id: motherboard
    modbus_id: modbus_motherboard
    address: 0x1
  - id: central_command
    modbus_id: modbus_central_command
    address: 0x1

# Reboot button 
button:
  - platform: restart
    name: "Reboot ESPHome Aldes"
    icon: mdi:power
    entity_category: diagnostic
    
#######################################################################################
#                    Sélection des modes de la PAC                                    #
#            (Ajustez à votre maison, avec clim ou sans clim)                         #
#######################################################################################
select:
  - platform: modbus_controller
    modbus_controller_id: motherboard
    id: "esp32_mode_air"
    name: "Mode air"
    icon: "mdi:hvac"
    address: 0x007A
    value_type: U_WORD
    use_write_multiple: true
    optimistic: true
    optionsmap:
      "off": 0
      "heat": 1   
      "Chauffage économique": 2
      "Programme chauffage A": 3
      "Programme chauffage B": 4
      "cool": 5    
      "Climatisation boost": 6 
      "Programme climatisation C": 7 
      "Programme climatisation D": 8 


####################################################################################### 
#               Temperature des pièces via ModBus de la commande centrale             #
#######################################################################################
sensor:
  - platform: modbus_controller
    modbus_controller_id: central_command
    name: "sejour temperature K1a"              # à adapter
    disabled_by_default: false                  # à adapter
    device_class: temperature
    state_class: measurement
    register_type: holding
    address: 190
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01
      
  - platform: modbus_controller
    modbus_controller_id: central_command
    name: "Chambre d'amis temperature K2"       # à adapter
    disabled_by_default: false                  # à adapter
    device_class: temperature
    state_class: measurement
    register_type: holding
    address: 192
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: central_command
    name: "Chambre vide temperature K3"         # à adapter
    disabled_by_default: false                  # à adapter
    device_class: temperature
    state_class: measurement
    register_type: holding
    address: 193
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: central_command
    name: "Palier temperature K4 "              # à adapter
    disabled_by_default: false                  # à adapter
    device_class: temperature
    state_class: measurement
    register_type: holding
    address: 194
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: central_command
    disabled_by_default: false                  # à adapter
    name: "Chambre à coucher temperature K5"    # à adapter
    device_class: temperature
    state_class: measurement
    register_type: holding
    address: 195
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01
      
  - platform: modbus_controller
    modbus_controller_id: central_command
    disabled_by_default: false              # à adapter
    name: "Bureau temperature K6"           # à adapter
    id: "esp32_bureau_k6"
    device_class: temperature
    state_class: measurement
    register_type: holding
    address: 196
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: central_command
    disabled_by_default: true           # à adapter
    name: "Temperature K7"              # à adapter
    device_class: temperature
    state_class: measurement
    register_type: holding
    address: 197
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: central_command
    disabled_by_default: true           # à adapter
    name: "Temperature K8"              # à adapter
    device_class: temperature
    state_class: measurement
    register_type: holding
    address: 198
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: central_command
    disabled_by_default: true           # à adapter
    name: "Temperature K9"              # à adapter
    device_class: temperature
    state_class: measurement
    register_type: holding
    address: 199
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

# Temperature principale via ModBus carte mère
  - platform: modbus_controller
    modbus_controller_id: motherboard
    disabled_by_default: true                  # à adapter
    name: "Sejour temperature principale "
    device_class: "temperature"
    state_class: "measurement"
    register_type: holding
    address: 0x0078
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: motherboard
    name: "Version logiciel"
    disabled_by_default: true         # à adapter
    entity_category: diagnostic
    icon: mdi:package
    register_type: holding
    address: 0x0001
    value_type: U_WORD
    
  - platform: modbus_controller
    modbus_controller_id: motherboard
    name: "Identifiant IHM"
    disabled_by_default: true         # à adapter
    entity_category: diagnostic
    icon: mdi:identifier
    register_type: holding
    address: 0x000E
    value_type: U_DWORD

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    disabled_by_default: false                  # à adapter
    id: wifi_signal_db
    update_interval: 120s
    entity_category: "diagnostic"
    
  - platform: modbus_controller
    modbus_controller_id: motherboard
    id: mode_air
    internal: true
    register_type: holding
    address: 0x007A

  - platform: template
    name: "Max Temp Mode"
    id: max_temp_mode
    update_interval: 50s
    unit_of_measurement: "°C"
    lambda: |-
      if (id(esp32_mode_air).state == "off") {
        return 24.0; // Default max temperature for off
      } else if (id(esp32_mode_air).state == "heat" || id(esp32_mode_air).state == "Chauffage économique" || 
                 id(esp32_mode_air).state == "Programme chauffage A" || id(esp32_mode_air).state == "Programme chauffage B") {
        return 24.0; // Max temperature for heating modes
      } else {
        return 31.0; // Max temperature for cooling modes
      }

#######################################################################################
#             Ensemble des températures de consigne des thermostats                   #
#                       (Ajustez à votre maison)                                      #
#######################################################################################
number:
  - platform: modbus_controller
    modbus_controller_id: motherboard
    name: "sejour Thermostat K1a"
    icon: "mdi:thermostat"
    unit_of_measurement: "°C"
    address: 0x96
    value_type: U_WORD
    min_value: 0
    max_value: 31
    use_write_multiple: true
    multiply: 100

  - platform: modbus_controller
    modbus_controller_id: motherboard
    name: "Chambre d'amis Thermostat K2"
    icon: "mdi:thermostat"
    unit_of_measurement: "°C"
    address: 0x98
    value_type: U_WORD
    min_value: 0
    max_value: 31
    use_write_multiple: true
    multiply: 100

  - platform: modbus_controller
    modbus_controller_id: motherboard
    name: "Chambre vide Thermostat K3"
    icon: "mdi:thermostat"
    unit_of_measurement: "°C"
    address: 0x99
    value_type: U_WORD
    min_value: 0
    max_value: 31
    use_write_multiple: true
    multiply: 100

  - platform: modbus_controller
    modbus_controller_id: motherboard
    name: "Palier Thermostat K4"
    icon: "mdi:thermostat"
    unit_of_measurement: "°C"
    address: 0x9A
    value_type: U_WORD
    min_value: 0
    max_value: 31
    use_write_multiple: true
    multiply: 100

  - platform: modbus_controller
    modbus_controller_id: motherboard
    name: "Chambre à coucher Thermostat K5"
    icon: "mdi:thermostat"
    unit_of_measurement: "°C"
    address: 0x9B
    value_type: U_WORD
    min_value: 0
    max_value: 31
    use_write_multiple: true
    multiply: 100
    
  - platform: modbus_controller
    modbus_controller_id: motherboard
    name: "Bureau Thermostat K6"
    id: "esp32_climate_bureau_k6"
    icon: "mdi:thermostat"
    unit_of_measurement: "°C"
    address: 0x9C
    value_type: U_WORD
    min_value: 0
    max_value: 31
    use_write_multiple: true
    multiply: 100

  - platform: modbus_controller
    modbus_controller_id: motherboard
    disabled_by_default: true           # à adapter
    name: "Thermostat K7"
    icon: "mdi:thermostat"
    unit_of_measurement: "°C"
    address: 0x9D
    value_type: U_WORD
    min_value: 0
    max_value: 31
    use_write_multiple: true
    multiply: 100

  - platform: modbus_controller
    modbus_controller_id: motherboard
    disabled_by_default: true           # à adapter 
    name: "Thermostat K8"           
    icon: "mdi:thermostat"
    unit_of_measurement: "°C"
    address: 0x9E
    value_type: U_WORD
    min_value: 0
    max_value: 31
    use_write_multiple: true
    multiply: 100

  - platform: modbus_controller
    modbus_controller_id: motherboard
    disabled_by_default: true       # à adapter
    name: "Thermostat K9"
    icon: "mdi:thermostat"
    unit_of_measurement: "°C"
    address: 0x9F
    value_type: U_WORD
    min_value: 0
    max_value: 31
    use_write_multiple: true
    multiply: 100

  - platform: modbus_controller 
    modbus_controller_id: motherboard
    name: "Thermostat K1b"
    disabled_by_default: true           # à adapter    
    icon: "mdi:thermostat"
    unit_of_measurement: "°C"
    address: 0x97
    value_type: U_WORD
    min_value: 16
    max_value: 31
    use_write_multiple: true
    multiply: 100

  - platform: modbus_controller
    modbus_controller_id: motherboard
    disabled_by_default: true           # à adapter
    name: "Tarif HP"
    icon: mdi:currency-eur
    entity_category: config
    mode: box
    unit_of_measurement: "€"
    address: 0xA0
    value_type: U_WORD
    min_value: 0.05
    max_value: 1
    use_write_multiple: true
    multiply: 1000
    step: 0.001

  - platform: modbus_controller
    modbus_controller_id: motherboard
    disabled_by_default: true           # à adapter
    name: "Tarif HC"
    icon: mdi:currency-eur
    entity_category: config
    mode: box
    unit_of_measurement: "€"
    address: 0xA1
    value_type: U_WORD
    min_value: 0.05
    max_value: 1
    use_write_multiple: true
    multiply: 1000
    step: 0.001

binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: motherboard
    name: "Etat du filtre"
    device_class: problem
    entity_category: diagnostic
    icon: mdi:air-filter
    register_type: holding
    address: 0x0082

########################################################################################
##        Retour d'état des plénums de diffusion                                       #
########################################################################################
  - platform: gpio # bouche K1a
    name: "Sejour bouche K1a"
    disabled_by_default: false                  # à adapter
    device_class: opening
    icon: "mdi:hvac"
    pin:
      number: GPIO36      #ADC1-0 - à ajuster en fonction de votre PCB
      mode: INPUT
    filters:
      - delayed_on: 10000ms
      - delayed_off: 50000ms

  - platform: gpio # bouche K2
    name: "Chambre d'amis bouche K2"
    disabled_by_default: false                  # à adapter
    device_class: opening
    icon: "mdi:hvac"
    pin:
      number: GPIO39     #ADC1-3 - à ajuster en fonction de votre PCB
      mode: INPUT
    filters:
      - delayed_on: 10000ms
      - delayed_off: 50000ms

  - platform: gpio # bouche K3
    name: "Chambre vide bouche K3"
    disabled_by_default: false                  # à adapter
    device_class: opening
    icon: "mdi:hvac"
    pin:
      number: GPIO35      #ADC1-7 - à ajuster en fonction de votre PCB
      mode: INPUT
    filters:
      - delayed_on: 10000ms
      - delayed_off: 50000ms

  - platform: gpio # bouche K4
    name: "Palier bouche  K4"
    disabled_by_default: false                  # à adapter
    device_class: opening
    icon: "mdi:hvac"
    pin:
      number: GPIO33      #ADC1-5 - à ajuster en fonction de votre PCB
      mode: INPUT
    filters:
      - delayed_on: 10000ms
      - delayed_off: 50000ms

  - platform: gpio # bouche K5
    name: "Chambre à coucher bouche K5"
    disabled_by_default: false                  # à adapter
    device_class: opening
    icon: "mdi:hvac"
    pin:
      number: GPIO34      #ADC1-6 - à ajuster en fonction de votre PCB
      mode: INPUT
    filters:
      - delayed_on: 10000ms
      - delayed_off: 50000ms

  - platform: gpio # bouche K6
    name: "Bureau bouche K6"
    disabled_by_default: false                  # à adapter
    device_class: opening
    icon: "mdi:hvac"
    pin:
      number: GPIO32      #ADC1-4 - à ajuster en fonction de votre PCB
      mode: INPUT
    filters:
      - delayed_on: 10000ms
      - delayed_off: 50000ms
      
# Dans le cas où vous souhaitez obtenir l'information de la bouche K1b au lieu de K1a,
# commentez le premier élément "Bouche K1a" et décommentez les lignes suivantes.
#  - platform: gpio # bouche K1b
#    disabled_by_default: true           # à adapter 
#    name: "Bouche K1b"
#    device_class: opening
#    icon: "mdi:hvac"
#    pin:
#      number: GPIO36      #ADC1-0 à ajuster en fonction de votre PCB
#      mode: INPUT
#    filters:
#      - delayed_on: 10000ms
#      - delayed_off: 50000ms
#######################################################################################

text_sensor:
  - platform: modbus_controller
    modbus_controller_id: motherboard
    name: "Aiguillage vanne"
    icon: mdi:valve
    entity_category: diagnostic
    register_type: holding
    address: 0x0064
    raw_encode: HEXBYTES
    lambda: |-
      uint16_t value = modbus_controller::word_from_hex_str(x, 0);
      switch (value) {
        case 0: return std::string("Etat initial");
        case 1: return std::string("ECS");
        case 2: return std::string("Air");
        case 3: return std::string("Standby");
        case 4: return std::string("Standby sécurité");
        case 5: return std::string("En cours de modification");
        default: return std::string("Inconnu");
      }
      return x;
